version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    IMAGE_REPO_NAME_1: "karthickapp"
    IMAGE_REPO_NAME_2: "nginx"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS \
        --password-stdin 754450290666.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI_1=754450290666.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_1
      - REPOSITORY_URI_2=754450290666.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_2
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Repository URI 1: $REPOSITORY_URI_1"
      - echo "Repository URI 2: $REPOSITORY_URI_2"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Docker image for JAVA..."
      - cd JAVA
      - docker build -t $REPOSITORY_URI_1:$IMAGE_TAG .
      - cd ../NGINX
      - echo "Building the Docker image for NGINX..."
      - docker build -t $REPOSITORY_URI_2:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI_1:$IMAGE_TAG
      - docker push $REPOSITORY_URI_2:$IMAGE_TAG
      - echo "Writing image definitions file for downstream deployments..."
      - printf '[{"name":"java-container","imageUri":"%s"},{"name":"nginx-container","imageUri":"%s"}]' \
          $REPOSITORY_URI_1:$IMAGE_TAG $REPOSITORY_URI_2:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
