replicaCount: 1

angular:
  name: angular-app
  image:
    repository: "754450290666.dkr.ecr.us-east-2.amazonaws.com/nginx"
    tag: "latest"
  containerPort: 3000
  servicePort: 3000

java:
  name: java-app
  image:
    repository: "754450290666.dkr.ecr.us-east-2.amazonaws.com/karthickapp"
    tag: "latest"
  ports:
    - name: http
      containerPort: 8080
      servicePort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
