replicaCount: 1

angular:
  name: angular-app
  image:
    repository: "754450290666.dkr.ecr.us-east-2.amazonaws.com/nginx"
    tag: "latest"
  containerPort: 3000
  servicePort: 3000  # This will be the port your ClusterIP service exposes

java:
  name: java-app
  image:
    repository: "754450290666.dkr.ecr.us-east-2.amazonaws.com/karthickapp"
    tag: "latest"
  ports:
    - name: http
      containerPort: 8080
      servicePort: 8080  # This will be the port your ClusterIP service exposes

ingress:
  enabled: true
  annotations:
    # example annotations for nginx ingress controller, customize as needed
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.local  # This should match what you put in /etc/hosts or DNS
      paths:
        - path: /
          pathType: Prefix
          serviceName: angular-app
          servicePort: 3000
        - path: /narenapp
          pathType: Prefix
          serviceName: java-app
          servicePort: 8080
  tls: []
