---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angular.name }}
spec:
  selector:
    app: {{ .Values.angular.name }}
  ports:
    - port: {{ .Values.angular.servicePort }}
      targetPort: {{ .Values.angular.containerPort }}
      protocol: TCP
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.java.name }}
spec:
  selector:
    app: {{ .Values.java.name }}
  type: LoadBalancer
  ports:
    {{- range .Values.java.ports }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
    {{- end }}
